name: Build documentation and pack

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Open-CMSIS-Pack/gen-pack-action@9cab2ab138e909e93a3f051ab9a4675b52843a25
        with:
          doxygen-version: 1.13.2
          packchk-version: 1.4.1
          gen-doc-script: bash ./Documentation/Doxygen/gen_doc.sh
          doc-path: ./Documentation/html
          gen-pack-script: bash ./gen_pack.sh --no-preprocess
          gen-pack-output: ./output
          gh-pages-branch: gh-pages
          pack-artifact-format: zip
